// Empty UserAnalytics + ConversationAnalytics builders. Used by:
//   1. The `empty` demo scenario (lib/demo/scenarios.ts).
//   2. Live-mode hooks that need a typed initial state when no real data
//      has loaded yet (useUserAnalytics, useTeamExtendedAnalytics).
//
// Single source of truth so the empty shape stays in lockstep with the
// canonical schema. If you add a required field to UserAnalyticsSchema
// or ConversationAnalyticsSchema, add it here too.

import type { UserAnalytics, ConversationAnalytics } from '../apiSchemas.js';
import { DEFAULT_PERIOD_DAYS } from './baseline.js';
import { buildDaySpine } from './rng.js';

export function createEmptyAnalytics(periodDays = DEFAULT_PERIOD_DAYS): UserAnalytics {
  const days = buildDaySpine(periodDays);
  return {
    ok: true,
    period_days: periodDays,
    teams_included: 0,
    degraded: false,
    file_heatmap: [],
    files_touched_total: 0,
    files_touched_half_split: null,
    files_by_work_type: [],
    files_new_vs_revisited: { new_files: 0, revisited_files: 0 },
    daily_trends: days.map((day) => ({
      day,
      sessions: 0,
      edits: 0,
      lines_added: 0,
      lines_removed: 0,
      avg_duration_min: 0,
      completed: 0,
      abandoned: 0,
      failed: 0,
      cost: null,
      cost_per_edit: null,
    })),
    tool_distribution: [],
    outcome_distribution: [],
    daily_metrics: [],
    hourly_distribution: [],
    tool_daily: [],
    model_outcomes: [],
    tool_outcomes: [],
    completion_summary: {
      total_sessions: 0,
      completed: 0,
      abandoned: 0,
      failed: 0,
      unknown: 0,
      completion_rate: 0,
      prev_completion_rate: null,
    },
    tool_comparison: [],
    work_type_distribution: [],
    tool_work_type: [],
    file_churn: [],
    duration_distribution: [],
    concurrent_edits: [],
    member_analytics: [],
    member_analytics_total: 0,
    member_daily_lines: [],
    per_project_lines: [],
    per_project_velocity: [],
    retry_patterns: [],
    conflict_correlation: [],
    conflict_stats: { blocked_period: 0, found_period: 0, daily_blocked: [] },
    edit_velocity: [],
    memory_usage: {
      total_memories: 0,
      searches: 0,
      searches_with_results: 0,
      search_hit_rate: 0,
      memories_created_period: 0,
      stale_memories: 0,
      avg_memory_age_days: 0,
      pending_consolidation_proposals: 0,
      formation_observations_by_recommendation: { keep: 0, merge: 0, evolve: 0, discard: 0 },
      secrets_blocked_24h: 0,
    },
    work_type_outcomes: [],
    conversation_edit_correlation: [],
    file_rework: [],
    directory_heatmap: [],
    stuckness: {
      total_sessions: 0,
      stuck_sessions: 0,
      stuckness_rate: 0,
      stuck_completion_rate: 0,
      normal_completion_rate: 0,
    },
    file_overlap: { total_files: 0, overlapping_files: 0 },
    audit_staleness: [],
    first_edit_stats: {
      avg_minutes_to_first_edit: 0,
      median_minutes_to_first_edit: 0,
      by_tool: [],
    },
    memory_outcome_correlation: [],
    memory_per_entry_outcomes: [],
    top_memories: [],
    scope_complexity: [],
    prompt_efficiency: [],
    hourly_effectiveness: [],
    outcome_tags: [],
    tool_handoffs: [],
    period_comparison: {
      current: {
        completion_rate: 0,
        avg_duration_min: 0,
        stuckness_rate: 0,
        memory_hit_rate: 0,
        edit_velocity: 0,
        total_sessions: 0,
        total_estimated_cost_usd: null,
        total_edits_in_token_sessions: 0,
        cost_per_edit: null,
      },
      previous: null,
    },
    token_usage: {
      total_input_tokens: 0,
      total_output_tokens: 0,
      total_cache_read_tokens: 0,
      total_cache_creation_tokens: 0,
      avg_input_per_session: 0,
      avg_output_per_session: 0,
      sessions_with_token_data: 0,
      sessions_without_token_data: 0,
      total_edits_in_token_sessions: 0,
      total_estimated_cost_usd: 0,
      pricing_refreshed_at: null,
      pricing_is_stale: false,
      models_without_pricing: [],
      models_without_pricing_total: 0,
      cost_per_edit: null,
      cache_hit_rate: null,
      by_model: [],
      by_tool: [],
    },
    tool_call_stats: {
      total_calls: 0,
      total_errors: 0,
      error_rate: 0,
      avg_duration_ms: 0,
      calls_per_session: 0,
      research_to_edit_ratio: 0,
      one_shot_rate: 0,
      one_shot_sessions: 0,
      frequency: [],
      error_patterns: [],
      hourly_activity: [],
      host_one_shot: [],
    },
    commit_stats: {
      total_commits: 0,
      commits_per_session: 0,
      sessions_with_commits: 0,
      avg_time_to_first_commit_min: null,
      by_tool: [],
      daily_commits: [],
      outcome_correlation: [],
      commit_edit_ratio: [],
    },
    data_coverage: {
      tools_reporting: [],
      tools_without_data: [],
      coverage_rate: 0,
      capabilities_available: [],
      capabilities_missing: [
        'hooks',
        'tokenUsage',
        'conversationLogs',
        'toolCallLogs',
        'commitTracking',
      ],
    },
    confused_files: [],
    unanswered_questions: { count: 0 },
    cross_tool_handoff_questions: [],
    cross_tool_memory_flow: [],
    memory_aging: { recent_7d: 0, recent_30d: 0, recent_90d: 0, older: 0 },
    memory_categories: [],
    memory_single_author_directories: [],
    memory_supersession: { invalidated_period: 0, merged_period: 0, pending_proposals: 0 },
    memory_secrets_shield: { blocked_period: 0, blocked_24h: 0 },
  };
}

export function createEmptyConversation(periodDays = DEFAULT_PERIOD_DAYS): ConversationAnalytics {
  return {
    ok: true,
    period_days: periodDays,
    total_messages: 0,
    user_messages: 0,
    assistant_messages: 0,
    sentiment_distribution: [],
    topic_distribution: [],
    sentiment_outcome_correlation: [],
    sessions_with_conversations: 0,
    tool_coverage: { supported_tools: [], unsupported_tools: [] },
  };
}
