import type { WidgetDef } from '../types.js';

export const ACTIVITY_WIDGETS: WidgetDef[] = [
  {
    id: 'heatmap',
    name: 'activity heatmap',
    description: 'When you run sessions by hour and day of week',
    category: 'activity',
    scope: 'both',
    viz: 'heatmap',
    w: 8,
    h: 4,
    minW: 6,
    minH: 3,
    dataKeys: ['hourly_distribution'],
  },
  {
    id: 'work-types',
    name: 'work types',
    description: 'What kind of work: frontend, backend, test, docs, etc.',
    category: 'activity',
    scope: 'both',
    viz: 'proportional-bar',
    w: 4,
    h: 3,
    minW: 3,
    minH: 2,
    dataKeys: ['work_type_distribution'],
    fitContent: true,
  },
  {
    id: 'prompt-efficiency',
    name: 'prompt efficiency',
    description: 'Back-and-forth turns per edit over time — lower means fewer messages per change',
    category: 'activity',
    scope: 'both',
    viz: 'sparkline',
    w: 8,
    h: 3,
    minW: 4,
    minH: 2,
    dataKeys: ['prompt_efficiency'],
    fitContent: true,
  },
  {
    id: 'hourly-effectiveness',
    name: 'completion rate by hour',
    description: 'Completion rate and output by hour of day',
    category: 'activity',
    scope: 'both',
    viz: 'bar-chart',
    w: 8,
    h: 3,
    minW: 4,
    minH: 2,
    dataKeys: ['hourly_effectiveness'],
  },
  {
    id: 'work-type-outcomes',
    name: 'work type outcomes',
    description: 'Completion rate by work type',
    category: 'activity',
    scope: 'both',
    viz: 'bar-chart',
    w: 6,
    h: 3,
    minW: 4,
    minH: 2,
    dataKeys: ['work_type_outcomes'],
  },
];
