import type { WidgetDef } from '../types.js';

export const CODEBASE_WIDGETS: WidgetDef[] = [
  {
    id: 'commit-stats',
    name: 'commits',
    description: 'Hook-captured commits from agent sessions, rolled up across tools',
    category: 'codebase',
    scope: 'both',
    viz: 'stat-row',
    w: 6,
    h: 2,
    minW: 3,
    minH: 2,
    dataKeys: ['commit_stats'],
  },
  {
    id: 'directories',
    name: 'top directories',
    description: 'Top 10 directories by touch count, with per-directory completion rate',
    category: 'codebase',
    scope: 'both',
    viz: 'bar-chart',
    w: 6,
    h: 4,
    minW: 4,
    minH: 3,
    dataKeys: ['directory_heatmap'],
  },
  {
    id: 'files',
    name: 'top files',
    description: 'Top 10 files by touch count, with completion rate and line changes',
    category: 'codebase',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 4,
    minW: 4,
    minH: 3,
    dataKeys: ['file_heatmap'],
  },
  {
    id: 'file-churn',
    name: 'file churn',
    description: 'Top 10 files by session spread — persistent work across separate sessions',
    category: 'codebase',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 4,
    minW: 4,
    minH: 3,
    dataKeys: ['file_churn'],
  },
  {
    id: 'file-rework',
    name: 'file rework',
    description: 'Top 10 files by failed-edit ratio — candidates for refactor or review',
    category: 'codebase',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 4,
    minW: 4,
    minH: 3,
    dataKeys: ['file_rework'],
  },
  {
    id: 'audit-staleness',
    name: 'cold directories',
    description:
      'Directories with prior activity but no touches in 14+ days — ownership gaps and pruning candidates',
    category: 'codebase',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 3,
    minW: 4,
    minH: 2,
    dataKeys: ['audit_staleness'],
    timeScope: 'all-time',
  },
  {
    id: 'concurrent-edits',
    name: 'edit collisions',
    description: 'Top 10 files touched by multiple agents this period — coordination hotspots',
    category: 'codebase',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 3,
    minW: 4,
    minH: 2,
    dataKeys: ['concurrent_edits'],
  },
];
