import type { WidgetDef } from '../types.js';

export const TOOLS_WIDGETS: WidgetDef[] = [
  {
    id: 'cache-efficiency',
    name: 'cache hit rate',
    description: 'How much of each prompt is reused from cache instead of re-sent to the model',
    category: 'tools',
    scope: 'both',
    viz: 'stat',
    w: 3,
    h: 2,
    minW: 2,
    minH: 2,
    dataKeys: ['token_usage'],
  },
  {
    id: 'tools',
    name: 'tool comparison',
    description: 'AI tools in use, with sessions, edits, and how much data each tool captures',
    category: 'tools',
    scope: 'both',
    viz: 'factual-grid',
    w: 6,
    h: 3,
    minW: 3,
    minH: 2,
    dataKeys: ['tool_comparison'],
  },
  {
    id: 'models',
    name: 'models',
    description: 'Which models your agents use, split by the tool that ran them',
    category: 'tools',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 3,
    minW: 3,
    minH: 2,
    dataKeys: ['model_outcomes'],
  },
  {
    id: 'tool-outcomes',
    name: 'tool outcomes',
    description: 'Completion breakdown per tool',
    category: 'tools',
    scope: 'both',
    viz: 'bar-chart',
    w: 6,
    h: 3,
    minW: 4,
    minH: 2,
    dataKeys: ['tool_outcomes'],
  },
  {
    id: 'tool-handoffs',
    name: 'tool handoffs',
    description: 'Files that move between different tools',
    category: 'tools',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 3,
    minW: 4,
    minH: 2,
    dataKeys: ['tool_handoffs'],
  },
  {
    id: 'tool-calls',
    name: 'tool calls',
    description:
      'How often agents call tools, how often calls fail, and how much they read before editing',
    category: 'tools',
    scope: 'both',
    viz: 'stat-row',
    w: 6,
    h: 2,
    minW: 4,
    minH: 2,
    dataKeys: ['tool_call_stats'],
  },
  {
    id: 'tool-call-freq',
    name: 'tool call frequency',
    description:
      'Which underlying tools agents call most (Edit, Read, Grep, MCP tools) and how often they error',
    category: 'tools',
    scope: 'both',
    viz: 'bar-chart',
    w: 6,
    h: 4,
    minW: 4,
    minH: 3,
    dataKeys: ['tool_call_stats'],
  },
  {
    id: 'tool-call-errors',
    name: 'tool call errors',
    description: 'Recurring errors when agents run tools, grouped by tool and error message',
    category: 'tools',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 3,
    minW: 4,
    minH: 2,
    dataKeys: ['tool_call_stats'],
  },
  {
    id: 'token-detail',
    name: 'token usage',
    description: 'Token consumption by model and tool',
    category: 'tools',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 4,
    minW: 4,
    minH: 3,
    dataKeys: ['token_usage'],
  },
  {
    id: 'tool-daily',
    name: 'tool adoption',
    description: 'Daily session volume per tool — adoption and migration over time',
    category: 'tools',
    scope: 'both',
    viz: 'multi-sparkline',
    w: 8,
    h: 4,
    minW: 6,
    minH: 3,
    dataKeys: ['tool_daily'],
  },
  {
    id: 'tool-work-type',
    name: 'tool work mix',
    description: 'What kind of work each tool handles',
    category: 'tools',
    scope: 'both',
    viz: 'proportional-bar',
    w: 6,
    h: 4,
    minW: 4,
    minH: 3,
    dataKeys: ['tool_work_type'],
    fitContent: true,
  },
  {
    id: 'data-coverage',
    name: 'data coverage',
    description: 'Which analytics have real data yet and what to do to light up the rest',
    category: 'tools',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 4,
    minW: 4,
    minH: 3,
    dataKeys: ['data_coverage'],
    timeScope: 'live',
    fitContent: true,
  },
];
