import type { WidgetDef } from './types.js';

// Codebase widgets — the file/directory axis. Substrate-unique because
// chinmeister is the only place where one file's edit history fuses every
// tool, every agent, and outcome attribution.
export const CODEBASE_WIDGETS: WidgetDef[] = [
  {
    id: 'commit-stats',
    name: 'commits',
    description:
      'Commits your agents made this period, across every tool. The git-side proof that sessions are actually shipping. Captured for tools with hook integration.',
    category: 'codebase',
    scope: 'both',
    viz: 'stat-row',
    w: 6,
    h: 2,
    minW: 3,
    minH: 2,
    dataKeys: ['commit_stats'],
    drillTarget: { view: 'codebase', tab: 'commits', q: 'commits-headline' },
    requiredCapability: 'commitTracking',
  },
  {
    id: 'directories',
    name: 'top directories',
    description:
      'The 8 directories your agents work in most, with how often sessions there finish cleanly. The low-completion ones are the recurring trouble spots.',
    category: 'codebase',
    scope: 'both',
    viz: 'bar-chart',
    w: 6,
    h: 4,
    minW: 4,
    minH: 3,
    dataKeys: ['directory_heatmap'],
    drillTarget: { view: 'codebase', tab: 'directories', q: 'top-dirs' },
    ownsClick: true,
    requiredCapability: 'hooks',
  },
  {
    id: 'files',
    name: 'top files',
    description:
      'The 8 files your agents touched most this period, with completion rate and lines changed. The hotspots.',
    category: 'codebase',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 4,
    minW: 4,
    minH: 3,
    dataKeys: ['file_heatmap'],
    drillTarget: { view: 'codebase', tab: 'landscape', q: 'landscape' },
    ownsClick: true,
    requiredCapability: 'hooks',
  },
  {
    id: 'file-rework',
    name: 'files in failed sessions',
    description:
      "The 8 files that keep showing up in sessions that don't finish. The percentage is each file's fail rate: the share of its edits that landed inside non-completing sessions, not retry on the edit itself. Worth a careful look before editing again.",
    category: 'codebase',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 4,
    minW: 4,
    minH: 3,
    dataKeys: ['file_rework'],
    drillTarget: { view: 'codebase', tab: 'risk', q: 'failing-files' },
    ownsClick: true,
  },
  {
    id: 'audit-staleness',
    name: 'cold directories',
    description:
      'Directories that used to see activity but have not been touched in 14 days or more. Ownership gaps and good candidates for pruning.',
    category: 'codebase',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 3,
    minW: 4,
    minH: 2,
    dataKeys: ['audit_staleness'],
    timeScope: 'all-time',
    drillTarget: { view: 'codebase', tab: 'directories', q: 'cold-dirs' },
    ownsClick: true,
  },
  {
    id: 'concurrent-edits',
    name: 'edit collisions',
    description: 'The 8 files multiple agents touched most this period. Coordination hotspots.',
    category: 'codebase',
    scope: 'both',
    viz: 'data-list',
    w: 6,
    h: 3,
    minW: 4,
    minH: 2,
    dataKeys: ['concurrent_edits'],
    drillTarget: { view: 'codebase', tab: 'risk', q: 'collisions' },
    ownsClick: true,
  },
];
